### ISSUE TITLE
nested params

### ISSUE THREAD

**Issue by zonika** [learn-co-curriculum/sinatra-pigeon#14] opened 2015-08-26 18:55 UTC
Can you nest the params in the last test so that they reflect the nested structure in the form names? right now it's giving 
params = {
        :name   => "Cher Ami",
        :gender => "female",
        :color  => "green, blue",
        :lives  => "Paris"
      }
when it should be giving
params = {
:pigeon =>{
        :name   => "Cher Ami",
        :gender => "female",
        :color  => "green, blue",
        :lives  => "Paris"}
      }
thanks

**Comment by AnnJohn** [comment] 2015-08-27 13:24
Iceboxing for now

**Comment by aviflombaum** [comment] 2015-08-29 19:02
This is a duplicate of #10. Closing. Thanks very much for bringing this to our attention @zonika. I'm going to fix #10 now.

**Closed by aviflombaum** 2015-08-29 19:02 UTC
Labels: icebox
